### ISSUE TITLE
Missing status won't trigger Prey. Actions (such as alarms) do

### ISSUE THREAD

**Issue by fanuneza** [prey/prey-android-client#104]
# Problem

Setting an Android device to **Missing** does nothing. The app won't start reporting. If you trigger an action, then Prey will *wake up* and start running all queued instructions.

This was tested on an Android 5 Moto X 2nd Gen. Screen turned off.

# How it was detected.

- Massive user feedback. Successfully reproduced.

**Comment by oaliaga** [comment]
We need more information,  could not replicate the error

**Comment by fanuneza** [comment]
We could, actually. Just this morning. We heavily suspect Google Play Services.
