### ISSUE TITLE
cannot find veriable config (FileConfigReader.java : 25 )

### ISSUE THREAD

**Issue by liaq192** [prey/prey-android-client#110]
Hi , building the project leads to error in file  (FileConfigReader.java : 25 ) at R.raw.config.

**Comment by Eeshdaya** [comment]
Same here

**Comment by robberer** [comment]
I unable to build too, because of this error

**Comment by oaliaga** [comment]
Fix

**Comment by Midhun-edv** [comment]
not yet solved
