### ISSUE TITLE
QR code scanning does not work

### ISSUE THREAD

**Issue by rugk** [prey/prey-android-client#113]
Another QR code scanner on my phone works, but I also see why the QR code is difficult to scan:

1) There is no (or only a very small) quiet zone around the QR code.
2) The QR code is generally really small.

So I can't scan it.

**Comment by raliste** [comment]
Thank you for your feedback @rugk!  We are currently reviewing the QR ui implementation from both the client and the web interface. We should release an update within a couple of days. Stay tuned!

**Comment by rugk** [comment]
Is there a new release?

**Comment by Merovex** [comment]
The QR code does not work.
