### ISSUE TITLE
Hostname www.preyproject.com not verified?

### ISSUE THREAD

**Issue by shevbingo** [prey/prey-android-client#120]
I am having this error message when I try running Prey from Android Studio with a virtual device:

"Hostname www.preyproject.com not verified:\n    certificate: sha1/+0BWZ7p9XF/atuNIU4qZJZv6yhg=\n    DN: CN=preyproject.com,O=Prey\, Inc.,L=San Francisco,ST=California,C=US,2.5.4.17=#13053934313033,STREET=218 9th Street,2.5.4.5=#130735333037343635,1.3.6.1.4.1.311.60.2.1.2=#130844656c6177617265,1.3.6.1.4.1.311.60.2.1.3=#13025553,2.5.4.15=#0c1450726976617465204f7267616e697a6174696f6e\n    subjectAltNames: [preyproject.com, panel.preyproject.com, help.preyproject.com, solid.preyproject.com, control.preyproject.com, toshiba.preyproject.com, prey.io, clients1.preyproject.com]"

And idea?

**Comment by cyaconi** [comment]
Hi, 

It's because you're pointing to **www**.preyproject.com instead of **control**.preyproject.com or **solid**.preyproject.com which are the devices endpoint.

**Comment by shevbingo** [comment]
Thanks cyaconi.
I changed config file:
prey-subdomain=control

And it looks working now.
