### ISSUE TITLE
Unable to reach device

### ISSUE THREAD

**Issue by alinpascaru** [prey/prey-android-client#122]
Hello,

I have a problem and I did not find the answer anywhere:
The web app is "Unable to reach the device": 
![screenshot 2017-02-28 10 11 44](https://cloud.githubusercontent.com/assets/16986373/23397212/2f88b818-fda0-11e6-91af-dc13552ee41f.png)

This is not the first time I have seen this. It looks like the android application does not open with the phone or is closed by phone. I do not have any battery saver apps installed. I can not find any setting that closes the application Prey.

This are my location settings:
![screenshot_20170228-101549](https://cloud.githubusercontent.com/assets/16986373/23397164/f995767e-fd9f-11e6-8711-c9a61880a615.png)
![screenshot_20170228-101555](https://cloud.githubusercontent.com/assets/16986373/23397166/fc1854a2-fd9f-11e6-8ecc-339b8b5b78f4.png)

I have tested a Connectivity Test at:
- a. http://solid.preyproject.com/test: ![screenshot_20170228-100652](https://cloud.githubusercontent.com/assets/16986373/23397188/12cb9f7e-fda0-11e6-9313-37be130c4922.png)
- b. https://solid.preyproject.com/test: 
![screenshot_20170228-102201](https://cloud.githubusercontent.com/assets/16986373/23397344/bde30294-fda0-11e6-8119-edcb2a9ea6ef.png)

The location is found only if I open the app:
![screenshot 2017-02-28 10 26 36](https://cloud.githubusercontent.com/assets/16986373/23397281/728915d6-fda0-11e6-930f-2778e632a043.png)

Normally, the application should run in the background to be accessed and to report if the phone is stolen. This is not happening. 

Can you help, me please?

**Comment by i-am-bigmike** [comment]
I've got exactly the same problem on the Asus Zenfone ZB500KL of my son. It responds only when I launch the app manually.

**Comment by norseh** [comment]
The problem is solved if you configure the auto-start manager (manager to permit or deny background apps).
Image of icon: http://kmpic.asus.com/images/2015/08/29/f3767c8a-862b-49fe-946d-e2a28c1f0b9f.jpg
