### ISSUE TITLE
"Actions" feature does not work

### ISSUE THREAD

**Issue by newarifrh** [prey/prey-android-client#141]
I tried using the latest source code on github (ver. 1.9.9 - 1.9.10) and built it using Android Studio 3.3 with the Xiaomi Redmi Note 4 Mobile.

When doing gradle there is a Google-Services.json error message not found. I tried to make the file use my firebase account and the appropriate package name, "com.prey". Prey can be built and installed on my mobile. But the features that can be used only to get the location and even then sometimes it doesn't work. In addition, other features (Message, alarm, lock) do not work. The information on the panel is "This acton is pending".

![image](https://user-images.githubusercontent.com/40921368/51371704-888e0d80-1b2d-11e9-84cf-0f17ff8757ec.png)

Thank you

**Comment by cyaconi** [comment]
Hi @newarifrh,

Regarding the pending actions, this is because Prey uses push notifications to activate actions on devices, and since you're not signing your application with Prey's certificate, these notifications won't be received.

**Comment by newarifrh** [comment]
> Hi @newarifrh,
> 
> Regarding the pending actions, this is because Prey uses push notifications to activate actions on devices, and since you're not signing your application with Prey's certificate, these notifications won't be received.

thank you for answering sir.
So can I sign the application using the Prey certificate?

**Comment by fanuneza** [comment]
Hi there,

> So can I sign the application using the Prey certificate?

You cannot. Since you're compiling your own version of Prey, you'll need to create your own push server and your own certificate, which is different than the one on the image.

You can learn more here: https://firebase.google.com/docs/cloud-messaging/

**Comment by newarifrh** [comment]
> Hi there,
> 
> > So can I sign the application using the Prey certificate?
> 
> You cannot. Since you're compiling your own version of Prey, you'll need to create your own push server and your own certificate, which is different than the one on the image.
> 
> You can learn more here: https://firebase.google.com/docs/cloud-messaging/

Thank you for your answer.
