### ISSUE TITLE
Adding devices in the web panel shows wrong message when Internet is unavailable

### ISSUE THREAD

**Issue by FedericoPosada** [prey/prey-android-client#146]
Hi, I was testing how the app's features worked when the Internet was turned off at specific moments. I found out this scenario, where the web panel displays a wrong error message if you try to add a new device when the Internet is disabled.

Steps:
-Go into the web panel
-Wait until it fully loads
-Deactivate Internet (Wi-Fi and Mobile data)
-Try to add a device
-Response: (The message says: "You have reached the limit of devices in the free plan", but my account only has one device)

![image](https://user-images.githubusercontent.com/30988027/57269604-b2702f00-704d-11e9-9692-4ae5300d4a1d.png)

You can see that my account only has 1/3 devices, so the message shouldn't be that I have reached the limit.

**Comment by patriciojofre** [comment]
thanks for your report @FedericoPosada, we'll fix this as soon as possible.
