### ISSUE TITLE
no config.property in "prey-prey-android-client-9fcd0d7\res\raw" directory

### ISSUE THREAD

**Issue by wucb** [prey/prey-android-client#23]
com.prey.FileConfigReader.java:

InputStream is = ctx.getResources().openRawResource(R.raw.config);

this line "config cannot be resolved or is not a field"!

**Comment by fanuneza** [comment]
Hi, @wucb. We're (finally) catching up with our Android issues. If your problem persists, please feel free to reopen this.

Have a nice day!
