### ISSUE TITLE
Allow apk to be downloaded outside Google Play too.

### ISSUE THREAD

**Issue by Mikaela** [prey/prey-android-client#29]
I have [Impression I10 tablet], which doesn't have Google Play officially, so I cannot install Prey with it.

I have looked for the .apk, but neither [preyproject.com] or [GitHub downloads] section provides .apk file.

I install everything to that tablet with [F-Droid] and it would be nice to have Prey there. If I understood correctly, there are some [issues] which prevent Prey from getting there.

[Impression I10 tablet]:http://mkaysi.github.com/articles/complaining/ImpressionI10.html
[preyproject.com]:http://preyproject.com
[GitHub downloads]:https://github.com/prey/prey-android-client/downloads
[F-Droid]:https://f-droid.org/
[issues]:https://f-droid.org/wiki/page/com.prey

**Comment by fanuneza** [comment]
Hi, guys. I know it's terribly late, but I think it's still appropriate to explain why the APK is not availabe.

Prey for Android relies on Google Cloud Messaging. Without that software it won't be able to do anything, because it's what we use to push instructions from the Prey servers. If devices don't have Google Play, then they most probably won't have Google Cloud Messaging either. Providing the APK would be an invitation to a "Prey doesn't work" flow of issues and emails.

I'm closing this. Please feel free to reopen it in case you have further questions.

**Comment by IzzySoft** [comment]
Requesting reopen for the reason of corrected facts:

> If devices don't have Google Play, then they most probably won't have Google Cloud Messaging either.

Doesn't stand. There's the [microG Project](https://github.com/microg) (formerly known as NOGAPPS) available here on Github, which provides most GServices – especially GCM. I use that for almost 2 years now without issues (see [my article on it](https://android.izzysoft.de/articles/named/android-without-google-5a)). And it's not the "small niche product" – many "Google refusers" use it meanwhile, just check their XDA threads :)

So may I suggest to provide the `.apk` along with your `releases/` – and while waiting to be listed on F-Droid, I'd offer picking it up for [my F-Droid compatible repo](https://android.izzysoft.de/repo), where updates usually would be available within 24h?

**Comment by IzzySoft** [comment]
My last comment being more than 4 months ago: May I kindly ask for a statement, as you (understandingly) close new requests in favor of this? If it stays a "No", we'll have to live with that – but I'm still hoping for a "yes, with the next release" :stuck_out_tongue_winking_eye:

**Comment by rugk** [comment]
Any news here? I think Prey was over even available on F-Droid, but I could be wrong.

**Comment by IzzySoft** [comment]
With this issue dating from 2015, newer issues on the topic being closed as dupes to this one, and no comment for over 2 years, it looks like we're ignored and there's no interest. So I'm removing it from my pending list, and look out for alternatives.

Oh, and hi again, @rugk :stuck_out_tongue:

**Comment by Kristinita** [comment]
> So I'm removing it from my pending list, and look out for alternatives.

@IzzySoft , I'm sorry, what Prey alternative you currently using?

Thanks.

**Comment by IzzySoft** [comment]
@Kristinita I'm using none at the moment. I was just thinking about it. If I would use any, it should be open source and available outside of Playstore (preferably directly from the F-Droid main repo). Prey'd fit the first condition, but unfortunately doesn't fit the second and doesn't seem interested even. And not even *answering* to such requests in any way but simply *ignoring* it makes it seem a bad candidate.

And @rugk Prey is neither in the main repo nor in the archive of F-Droid, just checked to make sure. A look at the gradle file will tell you why (4 of the GMS dependencies @Kristinita was mentioning).

**Comment by WPFilmmaker** [comment]
Any news 2 years later?

**Comment by IzzySoft** [comment]
I gave up on Prey. Not even answering after 3 years (from my microG argument) is a clear statement to me ("we don't care"). As for the GMS argument, apart from microG if one has to use GCM here, there are alternatives – [as Tutanota](https://f-droid.org/tr/2018/09/03/replacing-gcm-in-tutanota.html) and other apps show.

They explain there that other projects did the same in different ways :
"We’ve made a research on how others (Signal, Wire, Conversations, Riot, Facebook, Mastodon) have been solving similar problems. We had several options in mind, including WebSockets, MQTT, Server Sent Events and HTTP/2 Server Push."

They finally chose SSE and succeeded. So if there's a will, there are possibilities to solve this. I'm just afraid there's no will here…

(PS: apologies if this sounds offending. It's not meant that way, it's "just" frustration)

**Comment by rugk** [comment]
Wut? What happened to this issue?

1. Why was it closed? An F-Droid/apk out of Google Play would still be nice.
2. How was it even closed? GitHub does not show which user closed it, which is not a thing GitHub allowed to do? Can one close an issue without saying who closed it? uhm wtf????

![grafik](https://user-images.githubusercontent.com/11966684/71625203-e30d6600-2be6-11ea-8959-a0df0b1636c8.png)

**Comment by rugk** [comment]
Wtttf? Now my comment is shown above the closing label???

![grafik](https://user-images.githubusercontent.com/11966684/71625344-95452d80-2be7-11ea-9e7b-0a40206be9c6.png)

See also this snapshot: https://archive.is/9JKZu

**Comment by rugk** [comment]
Okay, contacted GitHub support and reported this behavior/this issue as a bug here. :smile:

**Comment by IzzySoft** [comment]
@rugk scroll up a bit:

![Selection_127](https://user-images.githubusercontent.com/6781438/71629748-76529580-2bff-11ea-9c59-e09382667af0.png)

The label at the end of the thread is just a reminder – especially for cases like this where the discussion continues. And it's always at the end of the list, so you see it when creating a new comment.

**Comment by rugk** [comment]
Lol really, never noticed that? This must be new… really…

**Comment by rugk** [comment]
(Maybe it's because the user who closed it has since been deleted, i.e. is a ghost now.)

**Comment by IzzySoft** [comment]
So maybe we should then ping a team member who is a real person and has not been ghosted yet – like @oaliaga? A lot can happen in the 7 years since this issue was opened, even in the 4 years since it was ghosted. Maybe there's some hope left after all?

**Comment by rugk** [comment]
BTW about the bug reported to GitHub: I received this answer:
> It looks like we'll add that extra "This issue was closed" timeline event when the issue was closed by a user that's since deleted their account (@ghost). That event will always appear at the end of the issue, regardless of any new comments.
>
>I agree this is a little confusing and I'm going to pass this on as feedback to our team!
