### ISSUE TITLE
SMS is sent on every boot

### ISSUE THREAD

**Issue by eiz1** [prey/prey-android-client#32]
GT-I9300
Android 4.0.4
Kernel 3.0.15-928452

I'm tried "Active SIM detection". Set sms to my friend number just for try. I changed my sim to different operator laterly. Now on every boot it send sms to my friend phone.
Warn on SIM change is disabled
Contact to notify is dimmed
Assign to current SIM is not working.

**Comment by fanuneza** [comment]
Hi, @eiz1.

Sorry for taking to long. The SMS alert was deprecated, so this shouldn't happen again.
