### ISSUE TITLE
Importing into Eclipse

### ISSUE THREAD

**Issue by geniass** [prey/prey-android-client#34]
I don't know where else to post this, but anyway, I am trying to import this project into Eclipse (I thought I would try to debug a crash myself). So after spending about an hour getting the app to run (involving some weird stuff like renaming folders which worked, for some reason), the app now runs, but crashes at an even earlier point (after entering username & password). Logcat is not very helpful (http://pastebin.com/kQi8rpFV)

**Comment by fanuneza** [comment]
Hi, guys. We're (finally) catching up with our Android issues. If your problem persists, please feel free to reopen this.

Have a nice day!
