### ISSUE TITLE
prey not sending sms to any contact !!

### ISSUE THREAD

**Issue by devilcrab** [prey/prey-android-client#44]
Hello,
        when i choose a contact and it ask for "send an msg to contact"  i try sending message.. but i get reply "Does your device not support sms service ?"  crap ???

how come.. can anyone tell me a fix for this ? i was using master package making bit upgrade to it.. ;)

waiting for some help.

**Comment by fanuneza** [comment]
Please check this: https://github.com/prey/prey-android-client/issues/33#issuecomment-73296984
