### ISSUE TITLE
publish on f-droid market

### ISSUE THREAD

**Issue by elf-pavlik** [prey/prey-android-client#47]
http://f-droid.org
"The F-Droid Repository is an easily-installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The server contains the details of multiple versions of each application, and the Android client makes it easy to browse, install them onto your device, and keep track of updates."

it also has some discussion about prey and possible issues in making it available there:
http://f-droid.org/forums/topic/prey/

**Comment by fanuneza** [comment]
Please check this: https://github.com/prey/prey-android-client/issues/29#issuecomment-73296455
