### ISSUE TITLE
libGoogleAnalytics.jar

### ISSUE THREAD

**Issue by maquedam** [prey/prey-android-client#48]
Consider removing this library.

1) There is not a clear reference to the license of the library (either in https://developers.google.com/analytics/) I still doubt if free : (

2) Let us avoid tracking what users do with our applications. Privacy... is a human right.

¡Free as in freedom!

P.D. Consider adopting: Free (freedom) / Open source anti-theft solution for laptops, phones & tablets ¡This software is wonderful! : )

**Comment by fanuneza** [comment]
Hi, @maquedam. We already removed the library from Prey. Sorry for taking so long to answer, though.
