### ISSUE TITLE
Android Lock Screen Password Input Limited to 16 chars, but online control panel is not

### ISSUE THREAD

**Issue by JamesMcGuigan** [prey/prey-android-client#55]
Steps to reproduce:
- Enter a lock password in Prey online control panel of 17+ chars
- Trigger "missing" event
- Wait for phone to lock and present lock screen
- Type in the long password into lock screen

What should happen
- Should be able to type in the whole password
- Phone should enable

What actually happens
- Only first 16 chars of password can be typed in
- Phone does not unlock due to invalid password

Suggested fixes:
1. Limit online control panel password field to 16 chars
2. Remove 16 char limit from android lock field
3. Validate long password if first 16 chars match

Workarounds:
- In control panel, reset device status to "found"
- Remove lock screen option
- Trigger a new "missing" event
- Phone should unlock

**Comment by fanuneza** [comment]
Hi, guys.

We already fixed this. Sorry for taking so long :neutral_face:
