### ISSUE TITLE
No settings on 1.0.12

### ISSUE THREAD

**Issue by bagage** [prey/prey-android-client#60]
When opening Prey -> "Manage app settings", the old customisable items are not present anymore. Instead, there are only:
- Manage your Devices which opens the website
- Revoke extra permissions
- Detach device
- Prey for Android (not clickable).

Where should I change the settings on my phone?

**Comment by fanuneza** [comment]
Hi, @bagage.

Prey for Android was dramatically simplified to allow more people to use it. The zillion options it had were removed, and now it's completely managed from your Prey account. While some features are currently missing (Active SIM Detection, SMS Activation, Uninstall Password) we're working to get them implemented in our new web interface, so you can manage all Prey-related things from your Prey account and not from each device.
