### ISSUE TITLE
dealayed calling out with no internet connection

### ISSUE THREAD

**Issue by fimu** [prey/prey-android-client#62]
With no internet connection (no mobile data and no WiFi or other) dialling out takes about 10-15s dealay before it starts actually dialling. I believe it is in "src/com/prey/PreyConfig.java" on 869 line in "public boolean isOnline()" function where while condition is interpreted incorrectly.

**Comment by fanuneza** [comment]
Hi, @fimu. We're (finally) catching up with our Android issues. If your problem persists, please feel free to reopen this.

Have a nice day!
