### ISSUE TITLE
Prey not sending reports

### ISSUE THREAD

**Issue by giacmir** [prey/prey-android-client#7]
I'm using a kraun tablet with android 2.2

If I send the activation sms prey seems to read it and logs 

02-29 12:21:38.005: I/PREY(2028): SMS received: GO PREY
02-29 12:21:38.005: I/PREY(2028): EmuSms
02-29 12:21:38.015: I/PREY(2028): SMS Match!, waking up Prey right now!

EmuSms is the app I've used to simulate the SMS message (the tablet has any SIM installed at the moment)

Device is marked as missing in the control panel and I receive the confirmation email but no report are generated or sent even after waiting some hours

if I try to manually activate prey using the in-app menu option logcat receives this:

02-29 12:24:24.185: E/PREY(2028): Error while running job [1212142608] :Thread was intrrupted. Finishing Location NotifierAction
02-29 12:24:24.185: E/PREY(2028): com.prey.PreyException: Thread was intrrupted. Finishing Location NotifierAction
02-29 12:24:24.185: E/PREY(2028): 	at com.prey.actions.location.LocationNotifierAction.execute(LocationNotifierAction.java:90)
02-29 12:24:24.185: E/PREY(2028): 	at com.prey.actions.observer.ActionJob.run(ActionJob.java:81)
02-29 12:24:24.185: E/PREY(2028): 	at java.lang.Thread.run(Thread.java:1096)
02-29 12:24:24.185: E/PREY(2028): Caused by: java.lang.InterruptedException
02-29 12:24:24.185: E/PREY(2028): 	at java.lang.VMThread.sleep(Native Method)
02-29 12:24:24.185: E/PREY(2028): 	at java.lang.Thread.sleep(Thread.java:1306)
02-29 12:24:24.185: E/PREY(2028): 	at java.lang.Thread.sleep(Thread.java:1286)
02-29 12:24:24.185: E/PREY(2028): 	at com.prey.actions.location.LocationNotifierAction.execute(LocationNotifierAction.java:88)
02-29 12:24:24.185: E/PREY(2028): 	... 2 more

device is marked as missing in the control panel but again no reports are generated.

**Comment by fanuneza** [comment]
Hi, guys. We're (finally) catching up with our Android issues. If your problem persists, please feel free to reopen this.

Have a nice day!
