### ISSUE TITLE
Reports from guest users on Android 5 don't include any information (HS:android-guest-reports)

### ISSUE THREAD

**Issue by fanuneza** [prey/prey-android-client#77]
## Problem

Android 4 and newer support user sessions. Trying a Guest user on Android 5 critically limited Prey's functionality.

- Pictures are not taken.
- Wi-Fi information is not gathered.
- Location services are disabled by default so a dummy location is sent.

Only hardware information was accurate.

![screenshot 2015-02-25 18 36 14](https://cloud.githubusercontent.com/assets/401279/6381105/068bf2d6-bd15-11e4-9e35-b1ad37d78d4f.png)

## How it was detected

Testing as requested by a user.

## Suggested solution

Either to find out if it's possible to include more information, or rule out that it can't be done so we document it well.

## References

- https://secure.helpscout.net/conversation/73991775/14966/

**Comment by oaliaga** [comment]
Restrictions the system
