### ISSUE TITLE
Password validation fails complex passwords.

### ISSUE THREAD

**Issue by StevenLiekens** [prey/prey-android-client#8]
There is a bug in the android app that prevents me from logging in using a long, complex password with a mixture of upper and lower case letters, numbers and symbols (but no spaces).
I don't know at which point exactly the validation fails, but setting the following password on your prey account will prevent you from logging into the android app: TV!dU9axE3f!Af28W3G$cADstWyQkfcv (don't worry, I've changed my password before posting).

Short, easy to remember (and thus crack) passwords work without issues.

**Comment by fanuneza** [comment]
Hi, guys. We're (finally) catching up with our Android issues. If your problem persists, please feel free to reopen this.

Have a nice day!

**Comment by StevenLiekens** [comment]
Better late than never I suppose. Keep it up!

**Comment by nxmohamad** [comment]
Hi, I'm still getting this error and my password is not longer than 24 characters. I'm using Redmi 2 running on Mi7

**Comment by earthsound** [comment]
I ran into this after having to get my LG G4 replaced after it hit the bootloop bug. 

I fixed it by logging into the web panel via my desktop and removing the old LG G4 (there were already three devices on my account). 

Perhaps this error is returned for several different cases. Either way, a better error when you've reached your device number limit would be nice.
