### ISSUE TITLE
Typo on login/manage screen

### ISSUE THREAD

**Issue by boris** [prey/prey-android-client#80]
Issue reported by user on PR #79. I confirmed that the issue is valid on the latest version from the Android Play Store.

![screenshot_2015-03-18-21-00-55](https://cloud.githubusercontent.com/assets/537305/6722177/7433a81a-cdb4-11e4-8267-6ff5eb83ed15.png)

**Comment by fanuneza** [comment]
Fixed by https://github.com/prey/prey-android-client/pull/79
