### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Allanitomwesh** [prey/prey-android-client#82]
would be nice if you added your app to F-Droid. it is an open source repository of app and i prefer to get my apps there than play store.

**Comment by fanuneza** [comment]
Hi @Allanitomwesh,

This question was posted before, and you can find our answer here: https://github.com/prey/prey-android-client/issues/29#issuecomment-73296455

We'll probably implement a GCM-independent version of Prey. Then the APK will be freely available.
