### ISSUE TITLE
Custom privacy options for B2B accounts are ignored by the Android client

### ISSUE THREAD

**Issue by fanuneza** [prey/prey-android-client#83]
## Problem

We provide custom module activation for business accounts. This means that we can disable pictures altogether, or other features, if the customer request it. This works for laptops, but the Android client doesn't consider this when sending reports.

## How it was detected

Customer feedback. A Nexus 5 from an account with the below settings still sent pictures.

![screenshot 2015-04-17 10 42 13](https://cloud.githubusercontent.com/assets/401279/7203293/fe337e8a-e4ef-11e4-873f-9fcab3212831.png)

## Suggested solution

Make the Android client stick to the privacy options.

## Resources

- https://secure.helpscout.net/conversation/84644969/18595/

**Comment by oaliaga** [comment]
close
