### ISSUE TITLE
Prey relies on Google Play services

### ISSUE THREAD

**Issue by pizzamaker** [prey/prey-android-client#84]
Prey uses GCM, which means you need Google Play Store installed, that is, proprietary software. For this reason, it hasn't been included yet in the F-Droid repository (which only allows free software and is the default app repository on Replicant phones). Details here: https://f-droid.org/forums/topic/prey/

What good is free software if it relies on proprietary software to work?

**Comment by jasonspiro** [comment]
1.  Google Cloud Messaging (GCM) is, I believe, part of Google Mobile Services (GMS).  It isn't just closed-source.  It's also restricted.  If you want a license to use it, you must buy a device which includes it.  Say you buy an Android device without it preinstalled.  Well, now you're stuck.  Even if you offer to pay $1,000 to Google, they still might not sell you a GMS license.

2.  Does even part of Prey for Android work without GMS?

3.  Does there exist any drop-in replacement for GCM which uses another server?  For example, does F-Droid offer a GCM replacement which uses the F-Droid central server instead?

**Comment by patcon** [comment]
I'm not sure I find the sweeping comments here helpful, but fwiw, MQTT is a lightweight machine-to-machine protocol created for embedded IoT devices, which has been used with some success as a push framework without vendor lock-in (specifically for Facebook messenger)

Websockets can also work (how TextSecure is getting away from GCM), but they seem to consume more battery.

A few MQTT clients are available (I've seen good things about Paho), and MQTT servers are offered as SaaS, which might be helpful during any evaluation period before we attempt to self-host a server.

Anyhow, food for thought. I came here looking for F-Droid compat too

**Comment by pizzamaker** [comment]
Are there any free replacements for Google Cloud Messaging? Is it even crucial for it to be included?

**Comment by Funatiker** [comment]
> there are tons of good reasons to use GCM if your target users are normal people
Could you please not imply that Non-Google-Android-Users are abnormal?

**Comment by pizzamaker** [comment]
Tutanota is grappling with the same issue, and some alternatives have been proposed: https://tutanota.uservoice.com/forums/237921-general/suggestions/8619142-don-t-rely-on-gcm-for-push-notifications-on-androi

**Comment by patcon** [comment]
I am a nogapps user, but I am not normal :/

**Comment by breversa** [comment]
Some of my devices have Google Play Services, but some do not. Am I normal or not ?

Rhetorical question aside, I believe that relying on GCM/GMS cuts Prey from a lot of users that have no-Gapps devices (or just do NOT want Google into their lives).

**Comment by agilob** [comment]
+1 for removing that dependency. Pray is aimed to people who prefer opensource solutions than proprietary google/facebook. If I wanted to use google dependency I would choose androidLost which is 100% based on google services (and well... offers more functionality).

**Comment by zeorin** [comment]
BTW for anyone that's interested there is a free software project for nogapps phones to still use GCM without having to install gapps: https://microg.org/

**Comment by skylarmt** [comment]
This got even worse recently, my phone started giving me notifications from Prey many times per day telling me to install Google Play Services.
