### ISSUE TITLE
Active SIM Detection inherited from an old version of Prey

### ISSUE THREAD

**Issue by beeatriz** [prey/prey-android-client#93]
## Problem

Active SIM Detection feature can't be removed and it keeps sending messages as the deactivation option isn't available any longer.

## How it was detected

User feedback.

## Suggestion

Completely remove the Active SIM Detection code from the Prey for Android app.

## References

https://secure.helpscout.net/conversation/86867848/19540/

**Comment by oaliaga** [comment]
Resolved https://github.com/prey/prey-android-client/releases/tag/v1.2.2
