### ISSUE TITLE
Prey for Android won't accept password

### ISSUE THREAD

**Issue by beeatriz** [prey/prey-android-client#96]
## Problem

When trying to log in on Prey for Android, or to even register the device, the password will be detected as invalid, even if it works for Panel.

Unable to replicate, not everyone has it and apparently fixable with re-install.
## How it was detected.

Plenty of user feedback. 
## Suggestion

Seek and destroy!
## References

https://secure.helpscout.net/conversation/95275022/22652/
https://secure.helpscout.net/conversation/100386726/24138/
https://secure.helpscout.net/conversation/103480828/24983/
## Model / Version / vPrey*

Moto G XT1045
Android 4.4.4
Prey version 1.2.9

Samsung Galaxy Core II SM-G355H
Android 4.4.2
Prey 1.2.9

Sony Z3
Android 5.0.2
Prey version 1.2.9

*Gathering data to find possible pattern

**Comment by suraphan** [comment]
Tong
