### ISSUE TITLE
Android KitKat not taking pics from front cam

### ISSUE THREAD

**Issue by beeatriz** [prey/prey-android-client#97]
## Problem

Samsung S3 Android KitKat 4.4.4 takes pictures from rear camera.
## How it was detected.

User feedback. 
## Suggestion

Look for possible bug to fix.
## References

https://secure.helpscout.net/conversation/102536352/24770/

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Does this application utilise an integrated camera/viewfinder?

**Comment by rokejulianlockhart** [comment]
Works for me with Android 11. Your device is probably too old or incorrectly implemented the relevant API.
