### ISSUE TITLE
MIUI phone failing to connect via Wi-Fi

### ISSUE THREAD

**Issue by beeatriz** [prey/prey-android-client#98]
## Problem
Xiaomi Hongmi phone using MIUI OS stops connecting to Prey everytime Wi-Fi is on, even though it works using mobile data network.

## How it was detected.
User feedback.

## Suggestion
Replicate the problem when we ever get our hand on a phone like that.

**Comment by boris** [comment]
Seems to me it's an issue the the proxy of the network... 
@beeatriz could you please verify with the user if this happens when it connects to any Wi-Fi network?

**Comment by beeatriz** [comment]
On it, I'll let you know when I have news.

**Comment by M9k** [comment]
Same problem with the last version of MIUI, chinese version.
